#!/usr/bin/env bash
# The one honest counter.
#
# Everything this script prints, it computed. The axiom/sorry claim is
# enforced at kernel level by NoGoals/Test/Axioms.lean during `lake build NoGoalsTest`
# (it fails the build on any undisclosed axiom, including sorryAx).
#
#   ./verify.sh          check mode: recompute counts, compare against README,
#                        exit 1 on drift (CI runs this)
#   ./verify.sh --write  splice freshly computed counts into README.md
#                        between the counts:begin/counts:end markers
#
# House rule (CLAUDE.md): never hand-write a count. This script is the only
# thing allowed to touch the README numbers.

set -euo pipefail
cd "$(dirname "$0")"

export PATH="$HOME/.elan/bin:$PATH"

MODE="${1:---check}"

echo "== build (proofs check during the build) =="
lake build
echo
echo "== tests + axiom audit (kernel-level sorry/axiom check) =="
lake build NoGoalsTest
echo

# --- counts (measured, never asserted) ---------------------------------------
PUBLIC_THEOREMS=$( (grep -rEh '^\s*theorem ' NoGoals --include='*.lean' || true) | wc -l | tr -d ' ')
PRIVATE_THEOREMS=$( (grep -rEh '^\s*private theorem ' NoGoals --include='*.lean' || true) | wc -l | tr -d ' ')
TOTAL_THEOREMS=$((PUBLIC_THEOREMS + PRIVATE_THEOREMS))

# Belt-and-braces source-level sorry scan (the kernel check above is the real
# enforcement; this catches sorries in code that no target builds).
SORRY_HITS=$( (grep -rEn '^\s*sorry\s*$|:=\s*sorry\b|by\s+sorry\b' NoGoals --include='*.lean' || true) | wc -l | tr -d ' ')

NATIVE_DECIDE_FILES=$( (grep -rl 'native_decide' NoGoals --include='*.lean' || true) | wc -l | tr -d ' ')
MODULES=$(find NoGoals -name '*.lean' | wc -l | tr -d ' ')

COUNTS_LINE="**${TOTAL_THEOREMS} theorems** (${PUBLIC_THEOREMS} public + ${PRIVATE_THEOREMS} private helper lemmas) · **0 sorries** · **0 axioms** beyond Lean's standard three (\`native_decide\` uses disclosed by the build-time audit)"
COUNTS_LINE_JA="**定理${TOTAL_THEOREMS}件**（公開${PUBLIC_THEOREMS}件 + 非公開の補助補題${PRIVATE_THEOREMS}件）· **sorry 0件** · **Lean 標準の3公理以外の公理0件**（\`native_decide\` の使用はビルド時の監査で明示）"

echo "== counts =="
echo "  modules:                ${MODULES}"
echo "  theorems:               ${TOTAL_THEOREMS} (${PUBLIC_THEOREMS} public + ${PRIVATE_THEOREMS} private helpers)"
echo "  sorry (source scan):    ${SORRY_HITS}"
echo "  files w/ native_decide: ${NATIVE_DECIDE_FILES}"
echo

if [ "${SORRY_HITS}" != "0" ]; then
  echo "FAIL: source-level sorry found:" >&2
  grep -rEn '^\s*sorry\s*$|:=\s*sorry\b|by\s+sorry\b' NoGoals --include='*.lean' >&2
  exit 1
fi

# --- README splice / drift check ---------------------------------------------
# Each README carries the counts line in its own language between the markers.
splice() {
  local readme="$1" line="$2" current
  grep -qF 'counts:begin' "${readme}" || { echo "FAIL: ${readme} is missing the counts markers." >&2; exit 1; }
  current=$(sed -n '/counts:begin/,/counts:end/p' "${readme}" | sed '1d;$d')
  if [ "$MODE" = "--write" ]; then
    python3 - "${readme}" "${line}" <<'PY'
import re, sys
p, line = sys.argv[1], sys.argv[2]
s = open(p).read()
s = re.sub(r'(<!-- counts:begin[^>]*-->\n).*?(<!-- counts:end -->)',
           lambda m: m.group(1) + line + "\n" + m.group(2), s, flags=re.S)
open(p, 'w').write(s)
PY
    echo "${readme} counts updated."
  elif [ "${current}" != "${line}" ]; then
    echo "FAIL: ${readme} counts have drifted from reality." >&2
    echo "  README:   ${current}" >&2
    echo "  computed: ${line}" >&2
    echo "  (run ./verify.sh --write)" >&2
    exit 1
  else
    echo "${readme} counts match computed reality."
  fi
}
splice README.md "$COUNTS_LINE_JA"
splice README.en.md "$COUNTS_LINE"

# --- the site's counts (the same numbers, as Lean the site compiles) ----------
SITE_COUNTS=site/Site/Counts.lean
SITE_COUNTS_BODY="-- Generated by ../verify.sh --write. Do not edit: verify.sh fails on drift.
namespace NoGoalsSite.Counts
def theorems : Nat := ${TOTAL_THEOREMS}
def sorries : Nat := ${SORRY_HITS}
end NoGoalsSite.Counts"

if [ "$MODE" = "--write" ]; then
  printf '%s\n' "$SITE_COUNTS_BODY" > "$SITE_COUNTS"
  echo "${SITE_COUNTS} updated."
elif [ "$(cat "$SITE_COUNTS")" != "$SITE_COUNTS_BODY" ]; then
  echo "FAIL: ${SITE_COUNTS} has drifted from reality (run ./verify.sh --write)." >&2
  exit 1
else
  echo "${SITE_COUNTS} matches computed reality."
fi

echo
echo "verify.sh: all checks passed."
